path: 'semi-datasets/semi-det-agent/road-r'
train: 'train'
val: 'valid'

names: 
  0: 'Ped'
  1: 'Car'
  2: 'Cyc'
  3: 'Mobike'
  4: 'MedVeh'
  5: 'LarVeh'
  6: 'Bus'
  7: 'EmVeh'
  8: 'TL'
  9: 'OthTL'